Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../", "/electron-sdk"

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = "4096"
  end

$script = <<-SHELL
   sudo apt-get update && sudo apt-get upgrade -y
   sudo apt-get install gnupg2 -y

   sudo curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
   sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
   sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

   sudo apt-get update -y
   sudo apt-get install -y code
   sudo apt-get install -y git

   curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
   sudo apt-get install -y nodejs

   curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
   echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
   sudo apt update && sudo apt install yarn

   sudo apt-get install -y --no-install-recommends ubuntu-desktop
   wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
   sudo dpkg -i google-chrome-stable_current_amd64.deb
   sudo apt-get -f -y install
   sudo chown -R vagrant:vagrant /home/vagrant/*
   mkdir /home/vagrant/Desktop

sudo shutdown -h now
SHELL

  config.vm.provision "shell", inline: $script, privileged: false

end
