minVersion: 2.19.0
changelogPolicy: auto
versioning:
  policy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: registry
    sdks:
      npm:@sentry/electron:
  - name: github
