description: Webpack 5 app with contextIsolation and sandbox with preload
command: npm install && npm run build
condition: supportsContextIsolation && supportsSandbox
timeout: 120
skipEsmAutoTransform: true
