export type {
  Breadcrumb,
  BreadcrumbHint,
  ErrorEvent,
  Event,
  EventHint,
  Exception,
  PolymorphicRequest,
  SdkInfo,
  Session,
  SeverityLevel,
  Span,
  StackFrame,
  Stacktrace,
  Thread,
  User,
} from '@sentry/core';

export {
  addBreadcrumb,
  addEventProcessor,
  addIntegration,
  amqplibIntegration,
  anthropicAIIntegration,
  buildLaunchDarklyFlagUsedHandler,
  captureCheckIn,
  captureConsoleIntegration,
  captureEvent,
  captureException,
  captureFeedback,
  captureMessage,
  captureSession,
  close,
  connectIntegration,
  consoleIntegration,
  consoleLoggingIntegration,
  contextLinesIntegration,
  continueTrace,
  createConsolaReporter,
  createGetModuleFromFilename,
  createLangChainCallbackHandler,
  createSentryWinstonTransport,
  createTransport,
  cron,
  dataloaderIntegration,
  dedupeIntegration,
  endSession,
  eventFiltersIntegration,
  expressErrorHandler,
  expressIntegration,
  extraErrorDataIntegration,
  fastifyIntegration,
  featureFlagsIntegration,
  firebaseIntegration,
  flush,
  fsIntegration,
  functionToStringIntegration,
  generateInstrumentOnce,
  genericPoolIntegration,
  getActiveSpan,
  getAutoPerformanceIntegrations,
  getClient,
  getCurrentScope,
  getGlobalScope,
  getIsolationScope,
  getRootSpan,
  getSpanDescendants,
  getSpanStatusFromHttpCode,
  getTraceData,
  getTraceMetaTags,
  googleGenAIIntegration,
  growthbookIntegration,
  graphqlIntegration,
  hapiIntegration,
  honoIntegration,
  httpHeadersToSpanAttributes,
  httpIntegration,
  httpServerIntegration,
  httpServerSpansIntegration,
  // eslint-disable-next-line deprecation/deprecation
  inboundFiltersIntegration,
  initOpenTelemetry,
  instrumentAnthropicAiClient,
  instrumentGoogleGenAIClient,
  instrumentLangGraph,
  instrumentOpenAiClient,
  instrumentStateGraphCompile,
  instrumentSupabaseClient,
  isEnabled,
  isInitialized,
  kafkaIntegration,
  knexIntegration,
  koaIntegration,
  langChainIntegration,
  langGraphIntegration,
  lastEventId,
  launchDarklyIntegration,
  linkedErrorsIntegration,
  localVariablesIntegration,
  logger,
  lruMemoizerIntegration,
  metrics,
  modulesIntegration,
  mongoIntegration,
  mongooseIntegration,
  mysql2Integration,
  mysqlIntegration,
  nativeNodeFetchIntegration,
  NodeClient,
  nodeContextIntegration,
  onUnhandledRejectionIntegration,
  openAIIntegration,
  OpenFeatureIntegrationHook,
  openFeatureIntegration,
  parameterize,
  pinoIntegration,
  postgresIntegration,
  postgresJsIntegration,
  prismaIntegration,
  profiler,
  redisIntegration,
  requestDataIntegration,
  rewriteFramesIntegration,
  Scope,
  SEMANTIC_ATTRIBUTE_SENTRY_OP,
  SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN,
  SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE,
  SEMANTIC_ATTRIBUTE_SENTRY_SOURCE,
  SentryContextManager,
  setConversationId,
  setContext,
  setCurrentClient,
  setExtra,
  setExtras,
  setHttpStatus,
  setMeasurement,
  setNodeAsyncContextStrategy,
  setTag,
  setTags,
  setupConnectErrorHandler,
  setupExpressErrorHandler,
  setupFastifyErrorHandler,
  setupHapiErrorHandler,
  setupHonoErrorHandler,
  setupKoaErrorHandler,
  setUser,
  spanToBaggageHeader,
  spanToJSON,
  spanToTraceHeader,
  spotlightIntegration,
  startInactiveSpan,
  startNewTrace,
  startSession,
  startSpan,
  startSpanManual,
  statsigIntegration,
  supabaseIntegration,
  suppressTracing,
  systemErrorIntegration,
  tediousIntegration,
  trpcMiddleware,
  unleashIntegration,
  updateSpanName,
  validateOpenTelemetrySetup,
  winterCGHeadersToDict,
  withActiveSpan,
  withIsolationScope,
  withMonitor,
  withScope,
  wrapMcpServerWithSentry,
  zodErrorsIntegration,
} from '@sentry/node';

export type { NodeOptions } from '@sentry/node';

export { additionalContextIntegration } from './integrations/additional-context.js';
export { browserWindowSessionIntegration } from './integrations/browser-window-session.js';
export { childProcessIntegration } from './integrations/child-process.js';
export { electronBreadcrumbsIntegration } from './integrations/electron-breadcrumbs.js';
export { electronContextIntegration } from './integrations/electron-context.js';
export { electronMinidumpIntegration } from './integrations/electron-minidump.js';
export { electronNetIntegration } from './integrations/net-breadcrumbs.js';
export { gpuContextIntegration } from './integrations/gpu-context.js';
export { mainProcessSessionIntegration } from './integrations/main-process-session.js';
export { normalizePathsIntegration } from './integrations/normalize-paths.js';
export { onUncaughtExceptionIntegration } from './integrations/onuncaughtexception.js';
export { preloadInjectionIntegration } from './integrations/preload-injection.js';
export { rendererEventLoopBlockIntegration } from './integrations/renderer-anr.js';
export { rendererProfileFromIpc } from './integrations/renderer-profiling.js';
export { screenshotsIntegration } from './integrations/screenshots.js';
export { sentryMinidumpIntegration } from './integrations/sentry-minidump/index.js';
export { startupTracingIntegration } from './integrations/startup-tracing.js';

export { makeElectronOfflineTransport } from './transports/electron-offline-net.js';
export { makeElectronTransport } from './transports/electron-net.js';

export { defaultStackParser } from './stack-parse.js';
export type { ElectronMainOptions } from './sdk.js';
export { getDefaultIntegrations, init } from './sdk.js';

export { IPCMode } from '../common/ipc.js';
