description: Electron Forge Webpack with contextIsolation and sandbox
command: npm install && npm run package
condition: supportsContextIsolation && supportsSandbox
timeout: 120
skipEsmAutoTransform: true
