import * as logger from './log.js';
import * as metrics from './metric.js';

export { logger, metrics };

export type {
  Breadcrumb,
  BreadcrumbHint,
  ErrorEvent,
  Event,
  EventHint,
  Exception,
  SdkInfo,
  Session,
  SeverityLevel,
  StackFrame,
  Stacktrace,
  Thread,
  User,
} from '@sentry/core';

export {
  MULTIPLEXED_TRANSPORT_EXTRA_KEY,
  addBreadcrumb,
  addEventProcessor,
  addIntegration,
  breadcrumbsIntegration,
  browserApiErrorsIntegration,
  BrowserClient,
  browserProfilingIntegration,
  browserSessionIntegration,
  browserTracingIntegration,
  buildLaunchDarklyFlagUsedHandler,
  captureConsoleIntegration,
  captureEvent,
  captureException,
  captureFeedback,
  captureMessage,
  captureSession,
  chromeStackLineParser,
  consoleLoggingIntegration,
  contextLinesIntegration,
  continueTrace,
  createConsolaReporter,
  createLangChainCallbackHandler,
  createTransport,
  createUserFeedbackEnvelope,
  dedupeIntegration,
  defaultRequestInstrumentationOptions,
  endSession,
  eventFiltersIntegration,
  eventFromException,
  eventFromMessage,
  exceptionFromError,
  extraErrorDataIntegration,
  featureFlagsIntegration,
  feedbackAsyncIntegration,
  feedbackIntegration,
  feedbackSyncIntegration,
  forceLoad,
  functionToStringIntegration,
  getActiveSpan,
  getClient,
  getCurrentScope,
  getFeedback,
  getGlobalScope,
  getIsolationScope,
  getReplay,
  getRootSpan,
  getSpanDescendants,
  getSpanStatusFromHttpCode,
  getTraceData,
  globalHandlersIntegration,
  graphqlClientIntegration,
  growthbookIntegration,
  httpClientIntegration,
  httpContextIntegration,
  // eslint-disable-next-line deprecation/deprecation
  inboundFiltersIntegration,
  instrumentAnthropicAiClient,
  instrumentGoogleGenAIClient,
  instrumentLangGraph,
  instrumentOpenAiClient,
  instrumentOutgoingRequests,
  instrumentSupabaseClient,
  isEnabled,
  isInitialized,
  lastEventId,
  launchDarklyIntegration,
  linkedErrorsIntegration,
  moduleMetadataIntegration,
  onLoad,
  openFeatureIntegration,
  OpenFeatureIntegrationHook,
  parameterize,
  registerSpanErrorInstrumentation,
  registerWebWorker,
  replayCanvasIntegration,
  replayIntegration,
  reportingObserverIntegration,
  reportPageLoaded,
  rewriteFramesIntegration,
  Scope,
  SEMANTIC_ATTRIBUTE_SENTRY_OP,
  SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN,
  SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE,
  SEMANTIC_ATTRIBUTE_SENTRY_SOURCE,
  sendFeedback,
  setActiveSpanInBrowser,
  setContext,
  setCurrentClient,
  setExtra,
  setExtras,
  setHttpStatus,
  setMeasurement,
  setTag,
  setTags,
  setUser,
  showReportDialog,
  spanToBaggageHeader,
  spanToJSON,
  spanToTraceHeader,
  spotlightBrowserIntegration,
  startBrowserTracingNavigationSpan,
  startBrowserTracingPageLoadSpan,
  startInactiveSpan,
  startNewTrace,
  startSession,
  startSpan,
  startSpanManual,
  statsigIntegration,
  supabaseIntegration,
  suppressTracing,
  thirdPartyErrorFilterIntegration,
  uiProfiler,
  unleashIntegration,
  updateSpanName,
  webWorkerIntegration,
  withActiveSpan,
  withIsolationScope,
  withScope,
  zodErrorsIntegration,
} from '@sentry/browser';

export type { BrowserOptions, ReportDialogOptions } from '@sentry/browser';

export { electronRendererStackParser as defaultStackParser } from './stack-parse.js';
export { eventLoopBlockIntegration } from './integrations/event-loop-block.js';
export { getDefaultIntegrations, init } from './sdk.js';
export { makeRendererTransport } from './transport.js';
export { scopeToMainIntegration } from './integrations/scope-to-main.js';
